version: '3.8'
services:
  chat-app-nginx:
    image: chat-app-nginx
    container_name: chat-app-nginx
    restart: always
    ports:
      - 80:80
    networks:
      - 5star_be
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  chat-app1:
    image: chat-app
    container_name: chat-app1
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_HOST: mongo2
      DB_PORT: 27017
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - 5star_be
    volumes:
      - /app/node_modules
      - ./:/app
  chat-app2:
    image: chat-app
    container_name: chat-app2
    restart: always
    environment:
      DB_HOST: mongo2
      DB_PORT: 27017
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - 5star_be
    volumes:
      - /app/node_modules
      - ./:/app
  chat-app3:
    image: chat-app
    container_name: chat-app3
    restart: always
    environment:
      DB_HOST: mongo2
      DB_PORT: 27017
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - 5star_be
    volumes:
      - /app/node_modules
      - ./:/app
  mongo2:
    image: mongo
    container_name: mongo2
    restart: always
    ports:
      - 27018:27017
    networks:
      - 5star_be
  redis:
    image: redis
    container_name: cache
    restart: always
    networks:
      - 5star_be
networks:
  5star_be:
    driver: bridge
